### PR TITLE
Add prefix to all MrVector attributes

### PR DESCRIPTION
**Pull request by dambrisco**
Bit of an ugly fix, and it breaks compatibility with http://ozodrukh.github.io/Svg2MrVector/, but does allow inclusion with other attr declarations.

### CODE REVIEW

**Comment by dambrisco** [comment]
Fixes #14

**Comment by eveliotc** [comment]
Thanks @dambrisco! do you mind using `mv_attribute` instead of `mvAttribute` so one just have to prepend `mv_` and not go nuts over camel case?

**Comment by dambrisco** [comment]
Done. Definitely makes more sense with `mv_`

**Comment by eveliotc** [comment]
Awesome, will deploy later today, thanks again @dambrisco!

**Comment by dambrisco** [comment]
I've also taken the liberty of re-creating the necessary MrVector support change off of a true fork of svg2android. It can be found here: http://dambrisco.github.io/svg2android/

I have a PR into svg2android, but I wouldn't be surprised if they turned it down. I'm happy to maintain it separately if they don't as it does have a few fixes that the version you currently link to doesn't.

**Comment by ozodrukh** [comment]
no, they will be glad to accept your PR, they already wrote to make PR with MrVector support, but i forgot  :(

**Comment by dambrisco** [comment]
@ozodrukh Yeah, I saw that and that's what actually prompted me to put that together. Hope you don't mind! Reading their updated README it sounded like they were looking to just support canonical VectorDrawable, but it'll be great if they do accept it.

**Pull request merged**
